spring:
  application:
    name: task-service                           # Unique name for this microservice

  datasource:
    url: jdbc:mysql://localhost:3306/task_db     # MySQL database URL
    username: root                               # MySQL username
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver

  jpa:
    hibernate:
      ddl-auto: update                           # Automatically updates the database schema
      dialect:  org.hibernate.dialect.MySQL5InnoDBDialect   # MySQL dialect for Hibernate (for MySQL 8+)
    show-sql: true                               # Show SQL queries for debugging
    properties:
      hibernate.format_sql: true                 # Formats SQL queries for better readability
      hibernate.use_sql_comments: true           # Add SQL comments in the generated queries

server:
  port: 8081  # Set server port to 8081

logging:
  level:
    org.springframework: INFO                   # General Spring log level
    org.hibernate.SQL: DEBUG                    # Log SQL queries at the DEBUG level
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Log SQL parameters
